# Generated by Django 5.2.13 on 2026-04-24 04:49

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('tools', 'Tools'), ('electronics', 'Electronics'), ('event_gear', 'Event gear'), ('sports', 'Sports'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles'), ('other', 'Other')], max_length=20)),
                ('district', models.CharField(choices=[('bektemir', 'Bektemir'), ('chilonzor', 'Chilonzor'), ('mirobod', 'Mirobod'), ('mirzo_ulugbek', 'Mirzo Ulugbek'), ('olmazor', 'Olmazor'), ('sergeli', 'Sergeli'), ('shaykhontohur', 'Shaykhontohur'), ('uchtepa', 'Uchtepa'), ('yakkasaray', 'Yakkasaray'), ('yashnabad', 'Yashnabad'), ('yunusobod', 'Yunusobod'), ('yangihayot', 'Yangihayot')], max_length=30)),
                ('price_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.listing_photo_upload_to)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.listing')),
            ],
            options={
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'is_active'], name='catalog_lis_categor_579bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['district', 'is_active'], name='catalog_lis_distric_4369f5_idx'),
        ),
    ]
