# Generated by Django 5.2.13 on 2026-04-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_booking_57d6de_idx',
            old_name='payments_pa_booking_45e2ec_idx',
        ),
    ]
